#!/usr/bin/env bash

git clone https://github.com/lachlan-ikeguchi/aerc ~/.config/aerc

echo "

#################################################################################################
Remember to export protonmail bridge TLS certificates and run 'sudo trust anchor --store' on them
#################################################################################################

"
