#!/usr/bin/env bash

git clone https://github.com/lachlan-ikeguchi/tmux ~/.config/tmux
mkdir ~/.config/tmux/plugins
mkdir ~/.config/tmux/plugins/tpm

git clone https://github.com/tmux-plugins/tpm.git ~/.config/tmux-tmp/
mv ~/.config/tmux-tmp/* ~/.config/tmux/plugins/tpm
rm -rf ~/.config/tmux-tmp
