#!/usr/bin/env bash

cd ~
git clone https://codeberg.org/ziglang/zig-bootstrap.git
cd zig-bootstrap/
./build native-linux-gnu native
cd out/
cd zig-native-linux-gnu-native/
cp ./zig ~/bin/zig
cp -r ./lib/ ~/bin/lib
