#!/usr/bin/env bash

sed -i '/############ added by script ############/,/#########################################/d' ~/.bash_aliases

cat >> ~/.bash_aliases <<'BLOCK'
############ added by script ############
# ---------- quality of life ---------- #
alias alias-edt='nvim ~/.bash_aliases'
alias bash-edt='nvim ~/.bashrc'
alias refresh='source ~/.bashrc'
alias grep='grep --color=auto'
alias l='ls -CFa'
alias ll='ls -la'
alias ls='ls --color=auto'
alias pub-ip='curl -s ident.me'
alias time='/usr/bin/time -v'
#########################################
BLOCK
